### ISSUE TITLE
RDF example notebook missing information

### ISSUE THREAD

**Issue by RainierBarrett** [glotzerlab/freud-examples#54]
In the module_intros/density.RDF-AccumulateFluid.ipynb notebook, there is the following line:
> The difference between accumulate (which should be called on a series of frames) and compute (meant for a single frame) is more striking for smaller bin sizes, which are statistically noisier.

However, the example in the cell below calls the same function for plotting RDFs defined in a previous cell, which does not feature any `accumulate` call. Is there a missing definition here, or just a change in how the `compute` method behaves?
As-is, it's a little confusing how to properly use this method going off of this doc, or how/whether `accumulate` should be used.

**Comment by tommy-waltmann** [comment]
Thanks for bringing this to our attention @RainierBarrett , the wording there is confusing and I suspect this example was not properly updated since the old freud 1.x days.

Since freud v2.x, accumulating an RDF over multiple frames of trajectory data is controlled through the `reset` argument to the compute method. See the documentation on that argument [here ](https://freud.readthedocs.io/en/v2.12.1/modules/density.html#freud.density.RDF.compute). When `reset=False`, data will be accumulated over multiple frames of trajectory data when `compute` is called multiple times in succession. When `reset=True` the RDF calculation will start over from scratch on each separate call to `compute`.

Hope this clears everything up, if you have any more questions feel free to ask!

**Comment by tommy-waltmann** [comment]
We'll update this example for the freud v3 release, since `RDF` underwent an API change on the main repository.

**Comment by RainierBarrett** [comment]
Great! Thanks :)

**Comment by tommy-waltmann** [comment]
We'll keep the issue open for tracking purposes. I'll close it after we update the example at some point in the future.
